---
title: "Fireveg-DB : Tables"
author: "Ferrer-Paris, J.R."
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
always_allow_html: true
---

# List of relations
Schema       |          Name           | Type  |  Owner
--------------------|-------------------------|-------|----------
  form               | field_samples           | table | jferrer
 form               | field_visit             | table | jferrer
 form               | fire_history            | table | jferrer
 form               | observerid              | table | jferrer
 form               | quadrat_samples         | table | jferrer
 litrev             | nsw_status              | table | jferrer
 litrev             | raw_annotations         | table | jferrer
 litrev             | traits                  | table | jferrer
 public             | Species_list            | table | jferrer
  public             | simple_ref_list         | table | jferrer


##  Table "public.Species_list"
Column     |       Type       | Collation | Nullable | Default
----------------+------------------+-----------+----------+---------
row.names      | text             |           |          |
SpeciesCode    | double precision |           |          |
FamilyName     | text             |           |          |
SortOrder      | double precision |           |          |
GenusName      | text             |           |          |
SpeciesName    | text             |           |          |
SubspeciesRank | text             |           |          |
SubspeciesName | text             |           |          |
ScientificName | text             |           |          |
PATNLabel      | text             |           |          |
CommonName     | text             |           |          |

### Indexes:
"name" btree ("ScientificName")

## Table "public.simple_ref_list"

Column  |          Type          | Collation | Nullable | Default
----------+------------------------+-----------+----------+---------
ref_code | character varying(100) |           | not null |
ref_cite | text                   |           |          |
ref_json | text                   |           |          |

### Indexes:
"simple_ref_list_pkey" PRIMARY KEY, btree (ref_code)

### Referenced by:
TABLE "litrev.raw_annotations" CONSTRAINT "raw_annotations_ref_fkey" FOREIGN KEY (ref_code) REFERENCES simple_ref_list(ref_code) ON UPDATE CASCADE ON DELETE CASCADE
TABLE "litrev.traits" CONSTRAINT "traits_ref_fkey" FOREIGN KEY (ref_code) REFERENCES simple_ref_list(ref_code) ON UPDATE CASCADE ON DELETE CASCADE

##  Table "litrev.nsw_status"
    Column    |          Type          | Collation | Nullable | Default
--------------+------------------------+-----------+----------+---------
 species      | character varying(255) |           |          |
 species_code | integer                |           | not null |
 common_name  | character varying(255) |           |          |
 nsw_status   | character varying(50)  |           |          |
 source       | text                   |           |          |
 access_date  | date                   |           |          |
### Indexes:
    "nsw_status_pkey" PRIMARY KEY, btree (species_code)

### Index "litrev.nsw_status_pkey"
    Column    |  Type   |  Definition
--------------+---------+--------------
 species_code | integer | species_code
primary key, btree, for table "litrev.nsw_status"

## Table "litrev.raw_annotations"
    Column    |          Type          | Collation | Nullable | Default
--------------+------------------------+-----------+----------+---------
 species      | character varying(255) |           | not null |
 species_code | integer                |           |          |
 attribute    | text                   |           | not null |
 value        | text                   |           |          |
 ref_code     | character varying(100) |           | not null |
 refs         | text[]                 |           |          |

### Indexes:
    "raw_annotations_pkey" PRIMARY KEY, btree (species, attribute, ref_code)

### Foreign-key constraints:
    "raw_annotations_ref_fkey" FOREIGN KEY (ref_code) REFERENCES simple_ref_list(ref_code) ON UPDATE CASCADE ON DELETE CASCADE

### Index "litrev.raw_annotations_pkey"
  Column   |          Type          | Definition
-----------+------------------------+------------
 species   | character varying(255) | species
 attribute | text                   | attribute
 ref_code  | character varying(100) | ref_code
primary key, btree, for table "litrev.raw_annotations"

##   Table "litrev.traits"
       Column       |          Type          | Collation | Nullable | Default
--------------------+------------------------+-----------+----------+---------
 species            | character varying(255) |           | not null |
 species_code       | integer                |           | not null |
 resprouting        | resprouting_types      |           |          |
 regenerative_organ | text[]                 |           |          |
 seedbank           | seedbank_type          |           |          |
 information_type   | text[]                 |           |          |
 ref_code           | character varying(100) |           |          |
 refs               | text[]                 |           |          |

### Indexes:
    "traits_pkey" PRIMARY KEY, btree (species, species_code)

### Foreign-key constraints:
    "traits_ref_fkey" FOREIGN KEY (ref_code) REFERENCES simple_ref_list(ref_code) ON UPDATE CASCADE ON DELETE CASCADE

### Index "litrev.traits_pkey"
    Column    |          Type          |  Definition
--------------+------------------------+--------------
 species      | character varying(255) | species
 species_code | integer                | species_code
primary key, btree, for table "litrev.traits"

##   Table "form.field_samples"
     Column      |         Type          | Collation | Nullable | Default
-----------------+-----------------------+-----------+----------+---------
 visit_id        | character varying(30) |           | not null |
 sample_nr       | smallint              |           | not null |
 sample_method   | sampling_method       |           |          |
 quadrat_area    | numeric               |           |          |
 transect_length | numeric               |           |          |
 comments        | text                  |           |          |
### Indexes:
    "field_samples_pkey" PRIMARY KEY, btree (visit_id, sample_nr)
### Foreign-key constraints:
    "field_samples_visit_id_fkey" FOREIGN KEY (visit_id) REFERENCES form.field_visit(visit_id) ON UPDATE CASCADE ON DELETE CASCADE

### Index "form.field_samples_pkey"
  Column   |         Type          | Definition
-----------+-----------------------+------------
 visit_id  | character varying(30) | visit_id
 sample_nr | smallint              | sample_nr
primary key, btree, for table "form.field_samples"

## Table "form.field_visit"
                Column                 |            Type             | Collation | Nullable | Default
---------------------------------------+-----------------------------+-----------+----------+---------
 visit_id                              | character varying(30)       |           | not null |
 visit_date                            | date                        |           |          |
 visit_description                     | text                        |           |          |
 location_description                  | text                        |           |          |
 geom                                  | geometry                    |           |          |
 elevation                             | numeric                     |           |          |
 plantcommunitytype                    | text                        |           |          |
 threatenedecologicalcommunity         | text                        |           |          |
 mainobserver                          | integer                     |           |          |
 otherobserver                         | character varying(20)       |           |          |
 tree_canopy_height_best               | numeric                     |           |          |
 tree_canopy_height_lower              | numeric                     |           |          |
 tree_canopy_height_upper              | numeric                     |           |          |
 tree_canopy_cover                     | numeric                     |           |          |
 tree_canopy_scorch_best               | numeric                     |           |          |
 tree_canopy_scorch_lower              | numeric                     |           |          |
 tree_canopy_scorch_upper              | numeric                     |           |          |
 mid_canopy_height_best                | numeric                     |           |          |
 mid_canopy_height_lower               | numeric                     |           |          |
 mid_canopy_height_upper               | numeric                     |           |          |
 mid_canopy_cover                      | numeric                     |           |          |
 mid_canopy_scorch_best                | numeric                     |           |          |
 mid_canopy_scorch_lower               | numeric                     |           |          |
 mid_canopy_scorch_upper               | numeric                     |           |          |
 shrub_height_best                     | numeric                     |           |          |
 shrub_height_lower                    | numeric                     |           |          |
 shrub_height_upper                    | numeric                     |           |          |
 shrub_cover                           | numeric                     |           |          |
 shrub_scorch_best                     | numeric                     |           |          |
 shrub_scorch_lower                    | numeric                     |           |          |
 shrub_scorch_upper                    | numeric                     |           |          |
 ground_burnt_best                     | numeric                     |           |          |
 ground_burnt_lower                    | numeric                     |           |          |
 ground_burnt_upper                    | numeric                     |           |          |
 ground_cover                          | numeric                     |           |          |
 tree_foliage_biomass_consumed_best    | numeric                     |           |          |
 tree_foliage_biomass_consumed_lower   | numeric                     |           |          |
 tree_foliage_biomass_consumed_upper   | numeric                     |           |          |
 shrub_foliage_biomass_consumed_best   | numeric                     |           |          |
 shrub_foliage_biomass_consumed_lower  | numeric                     |           |          |
 shrub_foliage_biomass_consumed_upper  | numeric                     |           |          |
 ground_foliage_biomass_consumed_best  | numeric                     |           |          |
 ground_foliage_biomass_consumed_lower | numeric                     |           |          |
 ground_foliage_biomass_consumed_upper | numeric                     |           |          |
 largest_twigs_consumed_best           | numeric                     |           |          |
 largest_twigs_consumed_lower          | numeric                     |           |          |
 largest_twigs_consumed_upper          | numeric                     |           |          |
 largest_twigs_consumed_raw            | character varying(255)      |           |          |
 peat_consumption_area                 | numeric                     |           |          |
 peat_consumption_maxdepth             | numeric                     |           |          |
 createdbysystemuserid                 | integer                     |           | not null |
 datecreated                           | timestamp without time zone |           | not null |
 updatedbysystemuserid                 | integer                     |           | not null |
 dateupdated                           | timestamp without time zone |           | not null |

### Indexes:
    "field_visit_pkey" PRIMARY KEY, btree (visit_id)
### Check constraints:
    "field_visit_check" CHECK (tree_canopy_height_best >= tree_canopy_height_lower AND tree_canopy_height_best <= tree_canopy_height_upper)
    "field_visit_check1" CHECK (tree_canopy_scorch_best >= tree_canopy_scorch_lower AND tree_canopy_scorch_best <= tree_canopy_scorch_upper)
    "field_visit_check10" CHECK (tree_foliage_biomass_consumed_best >= tree_foliage_biomass_consumed_lower AND tree_foliage_biomass_consumed_best <= tree_foliage_biomass_consumed_upper)
    "field_visit_check11" CHECK (shrub_foliage_biomass_consumed_best >= shrub_foliage_biomass_consumed_lower AND shrub_foliage_biomass_consumed_best <= shrub_foliage_biomass_consumed_upper)
    "field_visit_check12" CHECK (ground_foliage_biomass_consumed_best >= ground_foliage_biomass_consumed_lower AND ground_foliage_biomass_consumed_best <= ground_foliage_biomass_consumed_upper)
    "field_visit_check13" CHECK (largest_twigs_consumed_best >= largest_twigs_consumed_lower AND largest_twigs_consumed_best <= largest_twigs_consumed_upper)
    "field_visit_check2" CHECK (tree_canopy_scorch_upper <= tree_canopy_height_upper)
    "field_visit_check3" CHECK (mid_canopy_height_best >= mid_canopy_height_lower AND mid_canopy_height_best <= mid_canopy_height_upper)
    "field_visit_check4" CHECK (mid_canopy_scorch_best >= mid_canopy_scorch_lower AND mid_canopy_scorch_best <= mid_canopy_scorch_upper)
    "field_visit_check5" CHECK (mid_canopy_scorch_upper <= mid_canopy_height_upper)
    "field_visit_check6" CHECK (shrub_height_best >= shrub_height_lower AND shrub_height_best <= shrub_height_upper)
    "field_visit_check7" CHECK (shrub_scorch_best >= shrub_scorch_lower AND shrub_scorch_best <= shrub_scorch_upper)
    "field_visit_check8" CHECK (shrub_scorch_upper <= shrub_height_upper)
    "field_visit_check9" CHECK (ground_burnt_best >= ground_burnt_lower AND ground_burnt_best <= ground_burnt_upper)
### Foreign-key constraints:
    "field_visit_mainobserver_fkey" FOREIGN KEY (mainobserver) REFERENCES form.observerid(userkey) ON DELETE RESTRICT
### Referenced by:
    TABLE "form.field_samples" CONSTRAINT "field_samples_visit_id_fkey" FOREIGN KEY (visit_id) REFERENCES form.field_visit(visit_id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE "form.quadrat_samples" CONSTRAINT "quadrat_samples_visit_id_fkey" FOREIGN KEY (visit_id) REFERENCES form.field_visit(visit_id) ON UPDATE CASCADE ON DELETE CASCADE

### Index "form.field_visit_pkey"
  Column  |         Type          | Definition
----------+-----------------------+------------
 visit_id | character varying(30) | visit_id
primary key, btree, for table "form.field_visit"

## Table "form.fire_history"
       Column        |          Type          | Collation | Nullable | Default
---------------------+------------------------+-----------+----------+---------
 visit_id            | character varying(30)  |           | not null |
 fire_name           | character varying(100) |           |          |
 fire_date           | date                   |           | not null |
 fire_date_uncertain | interval               |           |          |
 how_inferred        | character varying(100) |           |          |
 cause_of_ignition   | character varying(100) |           |          |
### Indexes:
    "fire_history_pkey" PRIMARY KEY, btree (visit_id, fire_date)

### Index "form.fire_history_pkey"
  Column   |         Type          | Definition
-----------+-----------------------+------------
 visit_id  | character varying(30) | visit_id
 fire_date | date                  | fire_date
primary key, btree, for table "form.fire_history"

## Table "form.observerid"
        Column         |            Type             | Collation | Nullable |                     Default
-----------------------+-----------------------------+-----------+----------+--------------------------------------------------
 userkey               | integer                     |           | not null | nextval('form.observerid_userkey_seq'::regclass)
 givennames            | character varying(60)       |           |          |
 surname               | character varying(60)       |           | not null |
 addressline1          | character varying(50)       |           |          |
 addressline2          | character varying(50)       |           |          |
 city                  | character varying(30)       |           |          |
 postcode              | numeric(4,0)                |           |          |
 stateid               | integer                     |           |          |
 email                 | character varying(75)       |           |          |
 occupation            | character varying(40)       |           |          |
 notes                 | character varying(255)      |           |          |
 rowtimestamp          | timestamp without time zone |           | not null |
 createdbysystemuserid | integer                     |           | not null |
 datecreated           | timestamp without time zone |           | not null |
 updatedbysystemuserid | integer                     |           | not null |
 dateupdated           | timestamp without time zone |           | not null |

### Indexes:
    "observerid_pkey" PRIMARY KEY, btree (userkey)
### Referenced by:
    TABLE "form.field_visit" CONSTRAINT "field_visit_mainobserver_fkey" FOREIGN KEY (mainobserver) REFERENCES form.observerid(userkey) ON DELETE RESTRICT

### Index "form.observerid_pkey"
 Column  |  Type   | Definition
---------+---------+------------
 userkey | integer | userkey
primary key, btree, for table "form.observerid"

### Sequence "form.observerid_userkey_seq"
  Type   | Start | Minimum |  Maximum   | Increment | Cycles? | Cache
---------+-------+---------+------------+-----------+---------+-------
 integer |     1 |       1 | 2147483647 |         1 | no      |     1
Owned by: form.observerid.userkey

## Table "form.quadrat_samples"
         Column         |          Type          | Collation | Nullable |   Default
------------------------+------------------------+-----------+----------+------
 visit_id               | character varying(30)  |           |          |
 sample_nr              | smallint               |           |          |
 species                | character varying(255) |           |          |
 species_code           | integer                |           |          |
 agegroup               | age_group              |           |          |
 resprout_organ         | resprout_type          |           |          |
 seedbank               | seedbank_type          |           |          |
 resprouts_live         | numeric                |           |          |
 resprouts_died         | numeric                |           |          |
 resprouts_kill         | numeric                |           |          |
 resprouts_reproductive | numeric                |           |          |
 recruits_live          | numeric                |           |          |
 recruits_reproductive  | numeric                |           |          |
 recruits_died          | numeric                |           |          |
 comments               | text                   |           |          |
 record_id              | integer                |           | not null | nextval('form.quadrat_samples_record_id_seq'::regclass)
### Indexes:
    "quadrat_samples_pkey" PRIMARY KEY, btree (record_id)
### Foreign-key constraints:
    "quadrat_samples_visit_id_fkey" FOREIGN KEY (visit_id) REFERENCES form.field_visit(visit_id) ON UPDATE CASCADE ON DELETE CASCADE

### Index "form.quadrat_samples_pkey"
  Column   |  Type   | Definition
-----------+---------+------------
 record_id | integer | record_id
primary key, btree, for table "form.quadrat_samples"

### Sequence "form.quadrat_samples_record_id_seq"
  Type   | Start | Minimum |  Maximum   | Increment | Cycles? | Cache
---------+-------+---------+------------+-----------+---------+-------
 integer |     1 |       1 | 2147483647 |         1 | no      |     1
Owned by: form.quadrat_samples.record_id
